### ISSUE TITLE
Clear specs / dependencies list to make the example work. 

### ISSUE THREAD

**Issue by LouAdrien** [googollee/go-socket.io#219]
Hello, I tried both master and v1.4 branch. 
1) For master branch, the example simply does not work
2) For 1.4 branch, the example works, but adding a for loop that emits multiple messages to a socket, not all messages are actually emited (or received by the client). As it's just the default example I guess this comes from a dependency issue or something. 
Is there any specific dependencies on the go engine version? Anything else?
Thanks,

**Comment by erkie** [comment]
Thanks for the feedback. For master branch (at this point in time) you need a pretty old version of socket.io client JS: 0.9. v1.4 requires AFAIK the 1.4 version of socket.io. I would say with 95% certainty that is why it's not working correctly when you try. If not, please let me know.

Also, we're working on getting v1.4 merged at which point we can improve the documentation. My vision is that it will make it easier to support recent socket.io protocol versions. :)

**Comment by LouAdrien** [comment]
I took version 1.4.0 of socket.io client, this does not fixe the issue.
Side note, it seems more messages are coming back to the client when this one sends regular dumb message to the server, maybe there is a design flaw in the architect that waits for client message to emit waiting message to it?

Anyhow, do you have a working example of this repository being used in a real project? Or any more specifications on how to set it up? That would be appreciated, thanks

**Comment by LouAdrien** [comment]
Is there a requirement on the go version itself?

**Comment by erkie** [comment]
@LouAdrien AFAIK no go version constraint. Can you paste the code you are using? Also, just to be sure, you are using the v1.4 branch of this project with the 1.4 socket.io client right?

**Comment by erkie** [comment]
And now that we merged the 1.4 branch into master, things might be a bit different. Can you try using the code that is currently now in master?

**Comment by LouAdrien** [comment]
Hello, I just tried the latest code with its example, still not working, I created a pull request to reproduce the issue, hope this will help you solve it : https://github.com/googollee/go-socket.io/pull/221

**Comment by erkie** [comment]
Should be working now.
