### ISSUE TITLE
Calling Emit with a Second Parameter causes the connection to close

### ISSUE THREAD

**Issue by recfish** [googollee/go-socket.io#375]
**Describe the bug**
when I call Emit with a second parameter the socket connection is closed

**To Reproduce**
	server.OnEvent("/", "ping", func(s socketio.Conn) string {
		fmt.Println("ping")
		s.Emit("pong", "hi")
	})

**Expected behavior**
The message is sent and the connection does not close

**Environment (please complete the following information):**
 - Go version: v1.14.7
 - Server version go-socket.io v1.4
 - Client version socket.io for unity

**Additional context**
The client was able to receive messages from node JS. Errors:
websocket: close 1006 (abnormal closure): unexpected EOF
read tcp [::1]:8081->[::1]:50571: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by recfish** [comment]
This was solved by calling 
`strings.Replace(jsonStr, "\"", "", -1)`
so the format of the client and serve aligned.

**Comment by bugken** [comment]
hello.seems issue is still there. it happens when the client connections increasing. in my case, the client number exceed 15k or 12k, the issue will happen.
the solution you mentioned above. calling strings.Replace(jsonStr, "\"", "", -1) before emitting. so where should I put this line. pls help to show it. 
looking forward to your response. thank you  in advanced

Go version: v1.20
