### ISSUE TITLE
bug: memory leak happening.

### ISSUE THREAD

**Issue by piksonGit** [googollee/go-socket.io#442]
when i connect 170000+ clients using go-socket.io. 
the memory use keep growing even I just connect and do nothing.

**To Reproduce**
Brief code to reproduce the behavior.

**Expected behavior**
memory leak.  memory keep growing until oom.
**Environment (please complete the following information):**
 - Go version: [e.g. v1.16]
 - Server version [e.g. go-socket.io v1.4.5]

**Additional context**

server.OnEvent("/notification", "toServer", func(s socketio.Conn, msg interface{}) {

		noti := msg.(map[string]interface{})
----------

On Linux 3.10 centos7.

```
here is the heap.out
4729.28MB 28.89% 28.89%  4729.28MB 28.89%  bufio.NewWriterSize
 2924.13MB 17.86% 46.75%  2924.13MB 17.86%  bufio.NewReaderSize
 1416.50MB  8.65% 55.40%  1416.50MB  8.65%  bytes.makeSlice
  884.06MB  5.40% 60.80%   884.06MB  5.40%  io.copyBuffer
  861.35MB  5.26% 66.07%   912.86MB  5.58%  net/textproto.(*Reader).ReadMIMEHeader
  575.21MB  3.51% 69.58%   575.21MB  3.51%  runtime.malg
  568.47MB  3.47% 73.05%   568.47MB  3.47%  crypto/tls.Server
  389.62MB  2.38% 75.43%   389.62MB  2.38%  crypto/aes.(*aesCipherGCM).NewGCM
  275.08MB  1.68% 77.11%   298.08MB  1.82%  github.com/gorilla/websocket.newConn
  246.04MB  1.50% 78.62%   275.54MB  1.68%  github.com/googollee/go-socket.io/engineio/transport/websocket.newConn
```

here is the memestat:

```
 runtime.MemStats
# Alloc = 18400272336
# TotalAlloc = 169292392264
# Sys = 26073060600
# Lookups = 0
# Mallocs = 454336696
# Frees = 399619454
# HeapAlloc = 18400272336
# HeapSys = 18543607808
# HeapIdle = 63258624
# HeapInuse = 18480349184
# HeapReleased = 63258624
# HeapObjects = 54717242
# Stack = 6284509184 / 6284509184
# MSpan = 236746760 / 237682688
# MCache = 9600 / 16384
# BuckHashSys = 1938927
# GCSys = 880963976
# OtherSys = 124341633
# NextGC = 20642027808
# LastGC = 1620124870612394983

# NumForcedGC = 0
# GCCPUFraction = 0.08189029859571963
# DebugGC = false
# MaxRSS = 26046468096
```

I use gin and https

```

	web.Routes(router, server)
	router.RunTLS(":443", "./certification/*.infinitynewtab.com.pem", "./certification/*.infinitynewtab.com.key")
```

### the CLOSE_WAIT is too much and keep growing

213105 CLOSE_WAIT
     17 CLOSING
 181753 ESTABLISHED
     24 FIN_WAIT1
      2 FIN_WAIT2
    222 LAST_ACK
      7 LISTEN
    256 SYN_RECV
      1 SYN_SENT
     49 TIME_WAIT

**Comment by mrfoe7** [comment]
Hey, @piksonGit 
It does not actually?

**Comment by piksonGit** [comment]
> Hey, @piksonGit
> It does not actually?
yes, it's happening. my server have 64G memory. it ran out.

**Comment by mrfoe7** [comment]
I will try to fix this issue. Thanks you feedback

**Comment by piksonGit** [comment]
> I will try to fix this issue. Thanks you feedback

should I use s.Close() in OnDisconnect or OnError method?

**Comment by iGoogle-ink** [comment]
> I will try to fix this issue. Thanks you feedback

Is it fixed? I also encountered this problem！

**Comment by mrfoe7** [comment]
Hey, Jerry!
Sorry, for slow answer, it is in progress

**Comment by googollee** [comment]
To https://github.com/googollee/go-socket.io/issues/442#issuecomment-835250470, please call `Close()` in `OnError()` when you don't want to continue the session. It's also safe to call `Close()` in `OnDisconnect()`.

**Comment by iGoogle-ink** [comment]
> To [#442 (comment)](https://github.com/googollee/go-socket.io/issues/442#issuecomment-835250470), please call `Close()` in `OnError()` when you don't want to continue the session. It's also safe to call `Close()` in `OnDisconnect()`.

I will have a try

**Comment by piksonGit** [comment]
> > To [#442 (comment)](https://github.com/googollee/go-socket.io/issues/442#issuecomment-835250470), please call `Close()` in `OnError()` when you don't want to continue the session. It's also safe to call `Close()` in `OnDisconnect()`.
> 
> I will have a try

Do you fix the problems?

**Comment by iGoogle-ink** [comment]
> > > To [#442 (comment)](https://github.com/googollee/go-socket.io/issues/442#issuecomment-835250470), please call `Close()` in `OnError()` when you don't want to continue the session. It's also safe to call `Close()` in `OnDisconnect()`.
> > 
> > 
> > I will have a try
> 
> Do you fix the problems?

No，not solved

**Comment by jamaltan** [comment]
I also encountered this problem！
Hope for fixed it

**Comment by kingter-sutjiadi** [comment]
hi guys, anyone solved this issue?  anyway my swarm node stuck at 98% RAM Usage without any user on it anymore, am i facing the same problem or what?

**Comment by jialeo** [comment]
Is this problem fixed  now?

**Comment by dmskys** [comment]
Has the problem been solved? I have this problem, too?
      flat  flat%   sum%        cum   cum%
17990.09kB 36.10% 36.10% 17990.09kB 36.10%  bufio.NewWriterSize
15934.08kB 31.97% 68.07% 15934.08kB 31.97%  bufio.NewReaderSize
 6146.72kB 12.33% 80.40%  7682.75kB 15.42%  net/textproto.(*Reader).ReadMIMEHeader
 2048.40kB  4.11% 84.51%  2048.40kB  4.11%  github.com/googollee/go-socket.io/engineio/transport/websocket.newConn
 1536.03kB  3.08% 87.59%  1536.03kB  3.08%  net/textproto.canonicalMIMEHeaderKey
 1024.22kB  2.06% 89.65%  1024.22kB  2.06%  github.com/gorilla/websocket.newConn
 1024.12kB  2.05% 91.70%  1024.12kB  2.05%  net.newFD
 1024.09kB  2.05% 93.76%  1024.09kB  2.05%  net/textproto.(*Reader).ReadLine
  536.37kB  1.08% 94.83%   536.37kB  1.08%  regexp/syntax.(*compiler).inst
  526.13kB  1.06% 95.89%   526.13kB  1.06%  sync.(*Map).Store

**Comment by nkcc** [comment]
> 

I tried  call Close() in OnDisconnect(), but the sessions count still increase. Is there any solution for this problem?

**Comment by fsmytsai** [comment]
hello bro, is this problem fixed now?

**Comment by nkcc** [comment]
> 

nope,  there is a PR that commit by @sshaplygin , I have tried it. This problem still exists.

**Comment by piksonGit** [comment]
no update

Abanoub Istfanous ***@***.***> 于2022年5月5日周四 01:06写道：

**Comment by sshaplygin** [comment]
Hey, @piksonGit ! 
I merged fix for this problem. Please check up updates on this [version](https://github.com/googollee/go-socket.io/releases/tag/v1.6.2)

Do you have any time to check leak in your project?

**Comment by piksonGit** [comment]
> Hey, @piksonGit ! I merged fix for this problem. Please check up updates on this [version](https://github.com/googollee/go-socket.io/releases/tag/v1.6.2)
> 
> Do you have any time to check leak in your project?

hey.glad to hear that.I'll do test on my project. then I'll reply. thank you!

**Comment by piksonGit** [comment]
the problem is the same with before.
more and more CLOSE_WAIT 
then the program was killed.

**Comment by piksonGit** [comment]
> Hey, @piksonGit ! I merged fix for this problem. Please check up updates on this [version](https://github.com/googollee/go-socket.io/releases/tag/v1.6.2)
> 
> Do you have any time to check leak in your project?

my server go version is go1.15.5.
Should I upgrade my go version?

**Comment by sshaplygin** [comment]
> my server go version is go1.15.5.
Should I upgrade my go version?

if you can testing new version on part of your clients, you will upgrade to new version

**Comment by vortex92** [comment]
It seems to me that the problem is that after disconnecting the client from the server, the number of connections does not decrease.

With each new connection, an engineio.Server.session session is created in engineio.Server, and after the client is disconnected, the session does not go anywhere.

**Comment by jaygno** [comment]
Is it fixed? I also encountered this problem！on v1.6.2

**Comment by jqiris** [comment]
Is it fixed? I also encountered this problem！on v1.6.1
